### ISSUE TITLE
Error with String "Familiars"

### ISSUE THREAD

**Issue by jkydevelopment** [allansrc/string_to_hex#2]
When I try to generate a color with the String value `Familiars` its returned the next error:
```
#0      RangeError.checkValidRange (dart:core/errors.dart:350:7)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      StringToHex.toColor (package:string_to_hex/string_to_hex.dart:68:14)
#3      Utils.generateColorFromString (package:core/utils/utils.dart:327:39)

": Not in inclusive range 0..1"
```

**Comment by allansrc** [comment]
fixed by #3
